Capstone-project
Bupilipili/First-Capstone-Project pull request #2
Opened 2023-06-30 06:42 UTC by Bupilipili

###In this branch
-Made the website responsive using media queries.
-Created a mobile menu that pops up when clicked using Javascript.
-Created the speakers' section dynamically using Javascript.
-Created the website layout using CSS and HTML.
-Linked the home page with the website's logo.
-Linked the about page with the about in the nav bar.
-Updated the README.md file with current project details.
-Imported project images in the Features file.

2023-06-30 11:36 UTC, AlphaNtihinduka reviewed
Hi @Bupilipili ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
Invalid Code Review Request

You have submitted a project that does not have all the changes applied. Kindly ensure that the changes can be accessed in the PR by the code reviewer. This is to ensure to ensure that your codes can be easily reviewed ☺️ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-06-30 12:37 UTC, Bupilipili commented
@AlphaNtihinduka which changes are you talking about please be specific I don't understand you

2023-06-30 12:47 UTC, AlphaNtihinduka commented
Hello @Bupilipili , if you look at the changes available for the review. They don't reflect the whole project. This means that there are some lines of code I can not access for online review. I hope this comment clearly explains it. Thank you.

2023-06-30 13:35 UTC, Bupilipili commented
Hello, @AlphaNtihinduka I assure you that I have just added all the necessary changes for this project please review my work.

2023-06-30 14:03 UTC, osamaashraf6 requested changes
Hi @Bupilipili 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseAlmostGIF (3)](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/beba51dc-724c-4a19-9ce1-d9cf3a8d40bf)
## Highlights🎉🎉

- [ ] Nice design😊
- [ ] Has a live demo for the project🚀
- [ ] Iterate through the speakers using js to display it 💯





## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 14:03 UTC, osamaashraf6 commented on README.md
> +I would like to thank Microverse for giving me all the necessary knowledge I need to make this project.
- [x] While you make a great effort 😃 I see that you forgot to give the acknowledgments for the author of the original design, so please The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).💯😊

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>          <ul class="mobile-nav">
#### Kindly fix that at the header at both page's index and about 💯😃
- [x] Kindly 😃 it will be better if you increase the margin between the nav links as you see here it is less than the original design, so let's increase the margin to make it nice like the original design 💯😊
- [x] Also consider aligning the content of the header with the content of the sections as you see here the content of the header not starting with the content of the sections, so let's do that to make the design nice like the original design 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/6ec7c285-9f39-430b-89eb-85201872eeb3)  |   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/2a1395a5-cea7-4ed4-843a-71e9a82970dc)|

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>          <p class="word">FGE Ignite</p>
- [x] Kindly 😃 it will be better if you increase the margin-bottom of the text ```"Hello!Sharing world" ``` in the home page as you see here is not like the Behance design, so please try to increase it to make the design like the original design 😊💯
- [x] Also it will be better if you make the font-weight like the Behance as you see here it is thicker than the Behance design, so please try to decrease the font-weight to make it nice 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/b3b49edb-d957-4649-9071-c7cfa6818f9d) |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/7583e318-be36-4a22-b11a-75e785a085fc)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>          <p class="word">FGE Ignite</p>
- [x] Kindly 😃 try to decrease the font size of the paragraph as you see here it is greater than the Behance design, so let's decrease the font size of it to make the design nice like the Behance design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/b3dcdac2-3121-4574-8836-82c78539ab7d)  |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/237f08c4-61ad-4477-9db1-1c1da58d7397)   |

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>        <div>
- [x]  Kindly 😃 try to decrease the font size of the text here as you see here it is greater than the Behance design, so let's decrease the font size of it to make the design nice like the Behance design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/afe3bdd9-4c70-413a-9938-6703bb25d82e)  |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/b6ecab1d-e589-4ea0-af16-4e3fa106df85)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>        <div class="prog1">
- [x] While you make a great effort 😃 I see that you forgot to add the background image of this section on the page, so please try to add the background image for this section to make the design like the Behance 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/a650160a-61c6-421a-8838-58ec5aa38514) |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/c4d00d22-135c-4159-abf2-7caccf2a158d)|

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>        <div>
- [x] Kindly 😃 try to stick to the style for this part in the desktop version as you see here the style of this part is different from the style of the mobile version, so please try to change the style here to make it like a link with text-decoration underline to stick to the Behance design 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/678d385c-e410-430f-9ead-eed1bb8d67c5) |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/eac5bc9b-a28c-433a-aef3-7928419eabe6) |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>              <ul class="top-nav">
- [x] Kindly 😃 it will be better if you decrease the width of this text as you see here it is wider than the Behance design, so please try to decrease the width of this text to stick to the original design 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/03e5a1bd-8e81-460f-bc19-c2eb3b27d27e)  |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/5c4fd33a-f24b-4ca6-b8fd-37a81fdd2c3f)   |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>          <ul class="mobile-nav">
- [x] While you make a great effort 😃 I see that you forgot to add the background image of this section on the page, so please try to add the background image for this section to make the design like the Behance 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/68144574-e442-4517-81e9-475c21deb73a)  |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/df95a5ba-ba9d-4bfb-917b-0b7abc5e503d)|

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
> -            <a href="home.html"><img src="./Features/images/project-logo.png" alt="logo" class="logo"></a>
- [x] Kindly 😃 try to decrease the font size of the paragraph as you see here it is greater than the Behance design, so let's decrease the font size of it to make the design nice like the Behance design 😊💯
- [x] Also consider decreasing the padding of the container of this text as you see here it is greater than the Behance design and with that, the design will be great💯😊


> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/83d39a19-2da0-4504-acb9-9daf60a7469c)  |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/ff15205f-6e22-4587-ad96-6810741b31f4) |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>              <li class="nav-items"><a href="about.html">About</a></li>
- [x] While you make a great effort 😊I see that you put the partner section on the About page in the desktop version, but when I took a look at the Behance design I see that there is no partner section in the desktop version just it is existing in the mobile version s,o please try to fix that over the media query to control where you want the section to appear 😃💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/d84e3f9f-e937-447a-a053-3ce1b77dbeb1)  |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/4d35feaf-e0ca-4c18-842d-085e9f87a549) |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>            </div>
> I write the review here as I can not reach the specific code💯😊

- [x] While you make a great effort 😃 I see that you forgot to make the background color of the footer in the About page to be dark mode as you see here you made it light mode, so please try to change it to make the design like the Behance design 💯😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/025c2f28-6996-4100-bc1c-d5daddcbccb8)  |   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/ede8724e-395f-4e87-b5b4-e8217785bb97)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>            </div>
- [x] Kindly 😃 it will be better if you increase the margin-bottom of the text for two containers of images in the About page as you see here is not like the Behance design, so please try to increase it to make the design like the original design 😊💯
- [x] Also consider changing the background color of the images to be like the Behance design as you see here you made it grey but in the Behance design it seems orange, so please try to stick to the background color of it to make it nice like the Behance 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/4dedf33b-2019-42f7-a247-74e8cf9551ab)   |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/31e83345-73c8-4a81-bbdc-e3b3788fdae0)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>          </nav>
- [x] Kindly 😃 try to remove the logo of the header in the mobile version as you see here in your case it is existing in the header in the mobile version, so please try to remove it in the mobile version to be nice like the original design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/bfad4c64-39c6-4001-b138-b238d9d2a796)   |     ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/9d15fa20-0ace-41fe-89f6-a2f27ece3bde)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>            </div>
- [x] Kindly 😃 it will be better if you increase the margin-bottom of the text "Hello!Sharing world"  in the About page in the mobile version as you see here is not like the Behance design and is less than it, so please try to increase it to make the design like the original design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/efb5be7c-68c0-49b7-982e-f83347e2534f)  |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/529d1fb0-189b-409f-a73f-1efdbf63cc2f)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on about.html
>            </div>
- [x] Kindly 😃 it will be better if you increase the margin from both sides left and right of the paragraph in the About page in the mobile version as you see here is not like the Behance design, so please try to increase it to make the design like the original design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/ac18488d-9e81-49e4-8d4f-943d7b3875c9)    |   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/c1a3a72d-b5f3-4ae9-975e-43d002dcb1b3)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on index.html
>        <div class="prog1">
#### I write the review here as I can not reach the specific code💯😊

- [x] While you make a great effort I see that for the section main program, you used the div tag for wrapping the content, but in the requirements, it is said that put the content of each card in the main program inside the article tag, so please 😃try to do that It contains a middle section with a column that includes a section header, a divider, five individual articles, each with an image, title, and description, and a line of text at the bottom.

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| code of design | Your design| 
| --- | --- |
|  ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/61c42885-0e81-4c1f-8c52-8c485d8605d1)  |   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/77901464-306c-4512-a3d3-2e07f22e6472)  |

2023-06-30 14:03 UTC, osamaashraf6 commented on speakers.js
>      card.classList.add('speaker');
- [x] - [ ] While you make a great effort I see that for the section speakers, you used the div tag for wrapping the content, but in the requirements, it is said that put the content of each card in the speakers inside the article tag, so please 😃try to do that contains a bottom section with a column that includes a section header, a divider, and six individual articles, each with an image, title, subtitle, and description. Each article has two columns, the first with the image at the left and the second with the title, subtitle, and description.

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| code of design | Your design| 
| --- | --- |
|   ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/11c36628-0726-4313-95e1-64ff721134db)  |    ![image](https://github.com/Bupilipili/First-Capstone-Project/assets/83360636/81db7bd4-900f-4706-9689-438f2b9eacc0) |

2023-06-30 14:05 UTC, Bupilipili commented
Bro I need your help this is my last chance this week if I don't finish it
it's over for me,In my current project at first I had started working on
the main branch but later on I opened another branch by which in it I
opened a pull request now you say you don't see some code at that point
does it mean you want me to re-do everything again

On Fri, 30 Jun 2023, 15:48 NTIHINDUKA ALPHA, ***@***.***>
wrote:

> Hello @Bupilipili <https://github.com/Bupilipili> , if you look at the
> changes available for the review. They don't reflect the whole project.
> This means that there are some lines of code I can not access for online
> review. I hope this comment clearly explains it. Thank you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Bupilipili/First-Capstone-Project/pull/2#issuecomment-1614603947>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5WM6NPERYGIE7G6AXYXGVLXN3DIPANCNFSM6AAAAAAZZNWF5M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-30 21:50 UTC, tufoinnkuo10 requested changes
Hi @Bupilipili 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅Design well followed

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/KG5KpLlr1UEPvwgkiM/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-30 21:50 UTC, tufoinnkuo10 commented on about.html
> +            <li class="menu-items"><a href="index.html">Program</a></li>
- [optional] kindly ensure that the mobile menu disappears when switched to the desktop version. Also, consider adding a link to the home page in your mobile menu when in the about page. 
![Screenshot (1178)](https://github.com/Bupilipili/First-Capstone-Project/assets/65298048/5de56733-56f0-4273-b7fb-c294838fd2f9)

2023-06-30 21:50 UTC, tufoinnkuo10 commented on about.html
>              <div class="nav-flex">
- [ ] like the previous reviewer mentioned, kindly reduce the width of the main about page heading, make it bolder as well, so it matches the original design. 
- [ ] please, the text with white background below it in a rectangular box should have its width reduced as well as in the Behance design. Nice work.
yours
![Screenshot (1180)_LI](https://github.com/Bupilipili/First-Capstone-Project/assets/65298048/39227538-8b9c-4a64-8dd0-efa39f6bf720)
behance
![Screenshot (1181)](https://github.com/Bupilipili/First-Capstone-Project/assets/65298048/b9fd9bd9-240f-4ef8-be3b-6cd6ebf8014d)

2023-06-30 21:50 UTC, tufoinnkuo10 commented on index.html
>          <p class="word">Lecture</p>
- [ ] like the previous reviewer noted, kindly align the logo with the content of the page on the left, like in the original design. 
- [ ] please make the main title text weight bolder and add the font size if possible, so it looks like the original design. Also, kindly reduce the width of the text in the rectangle under the main title as proposed by the previous reviewer.
yours
![Screenshot (1176)_LI](https://github.com/Bupilipili/First-Capstone-Project/assets/65298048/bce8b3ca-4133-4196-9072-1701db65c174)
original
![Screenshot (1177)](https://github.com/Bupilipili/First-Capstone-Project/assets/65298048/e5cfb566-c09e-45e8-b6c3-c18583006295)

2023-07-01 05:40 UTC, abdallahmalima approved these changes
Hi @Bupilipili , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Home page and About page.✔️
- Mobile contain hamburger.✔️
- Project deployed.✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 05:42 UTC, merged